# Generated by Django 4.1.4 on 2022-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0002_alter_proposed_project_proposed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='budget_ratio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
