# Generated by Django 4.1.4 on 2022-12-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0003_alter_issue_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('completion', models.FloatField()),
                ('actual_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('dependancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observer.component')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('expected_cost', models.IntegerField()),
                ('timespan', models.IntegerField()),
                ('goal', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proposed_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.project_core')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='affiliated_agencies',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='project',
        ),
        migrations.AddField(
            model_name='agency',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='project_core',
            name='executing_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.agency'),
        ),
        migrations.AddField(
            model_name='project_core',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.location'),
        ),
        migrations.AddField(
            model_name='component',
            name='executing_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.agency'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.project_core'),
        ),
        migrations.AddField(
            model_name='approved_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.project_core'),
        ),
    ]
