# Generated by Django 4.1.4 on 2022-12-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observer", "0004_yearly_funding_constraint_location_constraint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="userType",
        ),
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="observer.agency",
            ),
        ),
        migrations.AlterField(
            model_name="proposed_project",
            name="proposed_date",
            field=models.DateField(),
        ),
    ]
