# Generated by Django 4.1.4 on 2022-12-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observer", "0004_approved_project_component_project_core_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("committee", models.CharField(max_length=20)),
                ("desciption", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="userType",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="observer.usertypes",
            ),
            preserve_default=False,
        ),
    ]
