# Generated by Django 4.1.4 on 2022-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observer", "0005_usertypes_user_usertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
        migrations.AlterField(
            model_name="agency",
            name="code",
            field=models.CharField(default="", max_length=50),
        ),
    ]
