# Generated by Django 4.1.4 on 2022-12-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0005_usertypes_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertypes',
            old_name='desciption',
            new_name='description',
        ),
    ]
