# Generated by Django 4.1.4 on 2022-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0006_rename_desciption_usertypes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposed_project',
            name='proposed_date',
            field=models.DateField(auto_now=True),
        ),
    ]
