# Generated by Django 4.1.4 on 2022-12-20 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_project',
            name='completion',
        ),
        migrations.AddField(
            model_name='agency',
            name='budget_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agency',
            name='last_usage_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='completion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='last_usage_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
