# Generated by Django 4.1.4 on 2022-12-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observer", "0010_alter_proposed_project_proposed_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "project_core",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observer.project_core",
                    ),
                ),
            ],
        ),
    ]
