# Generated by Django 4.1.4 on 2022-12-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0011_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_project',
            name='expected_end',
            field=models.DateField(null=True),
        ),
    ]
