# Generated by Django 4.1.4 on 2022-12-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0012_approved_project_expected_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypes',
            name='code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usertypes',
            name='committee',
            field=models.CharField(max_length=100),
        ),
    ]
